In [1]:
import math
import matplotlib
import datetime
import pandas as pd
import geopandas as gpd
import numpy as np
import ipywidgets as widgets

In [2]:
arbo_v = widgets.Combobox(
    placeholder = 'Selecione uma: ',
    options = ["Dengue", "Chikungunya", "Zika"],
    description = 'Arbovirose: ',
    ensure_option = True
)

display(arbo_v)

Combobox(value='', description='Arbovirose: ', ensure_option=True, options=('Dengue', 'Chikungunya', 'Zika'), …

In [3]:
arbo_v.value = str.lower(arbo_v.value)

In [4]:
aux = datetime.date.today()
aux = int(aux.strftime("%Y"))

if arbo_v.value == 'dengue':
    j = 10
else:
    j = 5

anos_aux = []
for i in range (aux-j, aux):
    anos_aux.append(str(i))

In [5]:
ano = widgets.Combobox(
    placeholder = 'Selecione o ano: ',
    options = anos_aux,
    description = 'Ano: ',
    ensure_option = True
)

display(ano)

Combobox(value='', description='Ano: ', ensure_option=True, options=('2012', '2013', '2014', '2015', '2016', '…

In [6]:
scr = f"../scr/{arbo_v.value}/"

if arbo_v.value == 'dengue':
    arq = scr + "casos_municipio_10.csv"
else:
    arq = scr + "casos_municipio_5.csv"

df = pd.read_csv(arq, encoding = "utf-8")
df = df.drop(columns=['Unnamed: 0'])

In [7]:
censo = pd.read_csv("../scr/BA - IBGE 2010.csv")
df["População 2010"] = 0

for i in range (len(df)):
    for j in range (len(censo)):
        if df.loc[i, "Município"] == censo.loc[j, "Município"]:
            df.loc[i, "População 2010"] = censo.loc[j, "População 2010"]

df["Casos_100.000hab"] = round(df.loc[:, f'{ano.value}']/df.loc[:, "População 2010"] * 100000, 0)

In [24]:
if arbo_v.value == "dengue":
    df["Obitos"] = 0
    obito = pd.read_csv("../scr/dengue/obitos_municipio_10.csv")
    for i in range (len(df)):
        for j in range (len(obito)):
            if df.loc[i, "Município"] == obito.loc[j, "Município"]:
                df.loc[i, "Obitos"] = obito.loc[j, ano.value]

In [25]:
df.head()

,Codigo,Município,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,População 2010,Casos_100.000hab,Obitos
0,290010,Abaíra,1,1,159,1,3,1,4,3,2,2,1,8316,12.0,0
1,290020,Abaré,4,4,0,4,22,27,6,0,226,321,2,17064,12.0,0
2,290030,Acajutiba,28,16,8,8,44,0,0,0,47,45,3,14653,20.0,0
3,290035,Adustina,119,331,64,109,34,71,8,21,96,40,9,15702,57.0,0
4,290040,Água Fria,14,21,34,0,12,3,1,4,95,106,1,15731,6.0,0

In [29]:
if arbo_v.value == "dengue":
    aux = df.nlargest(10, 'Casos_100.000hab')[['Codigo', 'Município', f'{ano.value}', 'População 2010', 'Casos_100.000hab', 'Obitos']]
else:
    aux = df.nlargest(10, 'Casos_100.000hab')[['Codigo', 'Município', f'{ano.value}', 'População 2010', 'Casos_100.000hab']]

aux

,Codigo,Município,2021,População 2010,Casos_100.000hab,Obitos
234,291955,Luís Eduardo Magalhães,4329,60105,7202.0,2
37,290320,Barreiras,6642,137427,4833.0,0
134,291110,Formosa do Rio Preto,861,22528,3822.0,0
15,290140,Angical,486,14073,3453.0,2
274,292270,Nova Canaã,565,16713,3381.0,0
268,292225,Muquém de São Francisco,325,10272,3164.0,0
54,290450,Brotas de Macaúbas,325,10717,3033.0,0
408,293315,Várzea Nova,344,13073,2631.0,0
158,291320,Ibotirama,603,25424,2372.0,0
286,292335,Ourolândia,365,16425,2222.0,0